Profile
BenBrownCreative/game-event-manager pull request #58
Opened 2020-09-05 02:48 UTC by BenBrownCreative

![image](https://user-images.githubusercontent.com/33357404/92296239-2cd9e900-eef8-11ea-8e3d-d431f744c686.png)

Top 10 games added to profile page header

2020-09-05 02:49 UTC, BenBrownCreative commented on client/src/components/GameFocused/index.js
> -              name="stopwatch"
just changing the icon here

2020-09-05 02:49 UTC, BenBrownCreative commented on client/src/components/GameFocused/components.js
> +  grid-template-columns: max-content;
styling tweek

2020-09-05 02:50 UTC, BenBrownCreative commented on client/src/components/GameImage/index.js
> +    p.selected ? p.theme.color.white : p.theme.color.darkGrey};
styling revision to add thin border and border radius to images per new figma mockup

2020-09-05 02:52 UTC, BenBrownCreative commented on client/src/components/Menu/index.js
> +      className: isCurrent ? 'selected' : ``
the console was whining about the classname not being set to a sting here. maybe there is a better solution but i was just trying to clean up the console and this seemed to do the trick.

2020-09-05 02:53 UTC, BenBrownCreative commented on client/src/components/typography/index.js
> -  font-size: ${p => (p.theme.size.phoneLarge ? '5rem' : '3rem')};
these font sizes were trying to set the media query size incorrectly

2020-09-05 03:31 UTC, meyer-mcmains requested changes
Let me know if you have any questions about that user query!

2020-09-05 03:31 UTC, meyer-mcmains commented on client/src/utils/queries/getTopTen.js
> +`;
instead of adding another query to just get the top then, you should instead use the user query to replace the get games query. This way you can get everything in one request. :rocket: 
Then you just pass the top ten as a prop to you component.

2020-09-05 03:31 UTC, meyer-mcmains commented on client/src/components/TopTen/index.js
> +  margin: 1rem 0 0 34px;
your margin left is redundant
```suggestion
  margin: 1rem 0 0 34px;
```

2020-09-05 03:31 UTC, meyer-mcmains commented on client/src/components/TopTen/index.js
> +  padding: 0;
instead of doing this I would set this in the global styles because if we use another `ul` we probably won't want the default padding their either.
```suggestion
```

2020-09-05 14:26 UTC, BenBrownCreative commented on client/src/utils/queries/getTopTen.js
> +`;
sounds good

2020-09-05 14:27 UTC, BenBrownCreative commented on client/src/components/TopTen/index.js
> +  margin: 1rem 0 0 34px;
over looked that

2020-09-05 14:27 UTC, BenBrownCreative commented on client/src/components/TopTen/index.js
> +  padding: 0;
good idea

2020-09-05 14:28 UTC, BenBrownCreative commented
I made the requested changes and added numbers to the top ten. Let me know if I combined the queries correctly.

![image](https://user-images.githubusercontent.com/33357404/92307192-1cf2f100-ef5a-11ea-9fe3-fd0bbb9884ee.png)

2020-09-06 01:57 UTC, meyer-mcmains requested changes

2020-09-06 01:57 UTC, meyer-mcmains commented on client/src/utils/queries/getUser.js
> +    }
You only need to pass the username once. I added games to the user query. So this is a single query for the user that includes whatever fields you ask for that are available.
![image](https://user-images.githubusercontent.com/8660578/92316427-5f97e600-efb9-11ea-90da-ba5b3153ca80.png)

so this needs to be:
```javascript 
query user(username: $username) {
      topTen
      games {
         name
         categories
         yearPublished
         image
         thumbnail
         id
         mechanics
         stats {
           maxPlaytime
           minPlaytime
           minPlayers
           maxPlayers
           suggestedPlayers
           averageWeight
         }
         rating {
           average
           user
           overallRank
         }
         url
         types
       }
    }

2020-09-06 13:09 UTC, BenBrownCreative commented on client/src/utils/queries/getUser.js
> +    }
i see. thanks for the help

2020-09-06 13:15 UTC, merged