Replace reach router with react router
BenBrownCreative/game-event-manager pull request #80
Opened 2020-09-16 18:12 UTC by BenBrownCreative

not sure if this will solve the refresh issue with profile pages in production. The routing should handle the same as it did with reach router. some small differences.

2020-09-16 22:29 UTC, meyer-mcmains requested changes

2020-09-16 22:29 UTC, meyer-mcmains commented on client/src/index.js
> +            renders the first one that matches the current URL. */}
```suggestion
```

2020-09-16 22:29 UTC, meyer-mcmains commented on client/src/pages/Home/index.js
> +const Home = props => {
```suggestion
const Home = ({ history }) => {
```

2020-09-16 22:29 UTC, meyer-mcmains commented on client/src/pages/Home/index.js
> +    props.history.push(`../profile/${username}`);
```suggestion
    history.push(`../profile/${username}`);
```

2020-09-17 14:33 UTC, BenBrownCreative commented on client/src/pages/Home/index.js
> +const Home = props => {
good call

2020-09-17 14:56 UTC, BenBrownCreative commented
i made the changes requested.

2020-09-18 03:49 UTC, meyer-mcmains approved these changes

2020-09-18 13:04 UTC, merged